'''

PKEAS-BM03

'''


# This file was *autogenerated* from the file ./Attack/BM03.sage
from sage.all_cmdline import *   # import sage library

_sage_const_123718923712936178236172831212381902312371892837122111111111111111 = Integer(123718923712936178236172831212381902312371892837122111111111111111); _sage_const_65537 = Integer(65537); _sage_const_123213 = Integer(123213); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0p25 = RealNumber('0.25')
N = _sage_const_123718923712936178236172831212381902312371892837122111111111111111 
e = _sage_const_65537 
d0 = _sage_const_123213 
kbits = _sage_const_10  # known bits
M = _sage_const_2  ** kbits # dp = d1 * M + d0

# LSBs
E = inverse_mod(e * M , N)
PR = PolynomialRing(Zmod(N), names=('x',)); (x,) = PR._first_ngens(1)

for k in range(_sage_const_1 ,e):
    print(k)
    f = E * (e * d0 + k - _sage_const_1 ) + x
    f.small_roots(X = Integer(N**(_sage_const_0p25 )))





